export const dataSearch = [
  { title: "Filtering of Leads", link: "/filtering-of-leads" },
  { title: "Call Flow and Spiels", link: "/call-flow-and-spiels" },
  { title: "Documentation", link: "/documentation" },
  { title: "Exception Handling", link: "/exception-handling" },
    { title: "Advisories", link: "/advisories" },
    { title: "New Campaigns (per product)", link: "/new-campaigns" },
    { title: "Promos (per product)", link: "/promos" },
    { title: "New Guidelines (per product)", link: "/new-guidelines" },
    { title: "Campaign Guidelines (per product)", link: "/campaign-guidelines" },
    { title: "Training", link: "/training" },
    { title: "Our Customers", link: "/our-customers" },
    { title: "Performance", link: "/performance" },
    { title: "Team Updates", link: "/team-updates" },
    { title: "Sales Support Corner", link: "/sales-support-corner" },
    { title: "Announcements", link: "/announcements" },
    { title: "Transmittal and Assignment Process", link: "/transmittal-and-assignment-process" },
    { title: "Validation Process", link: "/validation-process" },
    { title: "Guide to Handling Verifs", link: "/guide-to-handling-verifs" },
    { title: "Guide to Handling Deficiencies", link: "/guide-to-handling-deficiencies" },
    { title: "Sales Reports", link: "/sales-reports" },
    { title: "MIS", link: "/mis" },
    { title: "Quality Monitoring Corner", link: "/quality-monitoring-corner" },
    { title: "Top QM Performers", link: "/top-qm-performers" },
    { title: "QM Grades", link: "/qm-grades" },
    { title: "Commendations", link: "/commendations" },
    { title: "Table of Organization", link: "/table-of-organization" },
    { title: "Top Performers", link: "/top-performers" },
    { title: "Different Personas", link: "/different-personas" },
    { title: "Competitor Analysis", link: "/competitor-analysis" },
    { title: "Competitor Products", link: "/competitor-products" },
    { title: "Key Differentiators", link: "/key-differentiators" },
    { title: "Sales Tips for the Month", link: "/sales-tips-for-the-month" },
    { title: "FAQS", link: "/faqs" },
    { title: "Credit Cards", link: "/credit-cards" },
    { title: "SIP Loans", link: "/sip-loans" },
    { title: "Personal Loan", link: "/personal-loan" },
    { title: "Deposit Products", link: "/deposit-products" },
    { title: "Other Bank Products", link: "/other-bank-products" },
    { title: "Handling Objections", link: "/handling-objections" },
    { title: "Sales Reports", link: "/sales-reports" },
    { title: "Different Personas", link: "/different-personas" },
    { title: "Competitor Analysis", link: "/competitor-analysis" },
    { title: "Competitor Products", link: "/competitor-products" },
    { title: "Key Differentiators", link: "/key-differentiators" },
  ];
  
  // Example usage:
  console.log(dataSearch[0].title); // Outputs: "Advisories"
  console.log(dataSearch[0].link); // Outputs: "/advisories"
  